apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forkflow-local

resources:
  - ../../../base/fulfillment-service

commonLabels:
  environment: local

replicas:
  - name: fulfillment-service
    count: 2

images:
  - name: fulfillment-service
    newName: fulfillment-service
    newTag: latest

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: fulfillment-service
      spec:
        template:
          spec:
            containers:
              - name: fulfillment-service
                resources:
                  requests:
                    memory: "128Mi"
                    cpu: "100m"
                  limits:
                    memory: "256Mi"
                    cpu: "500m"
                env:
                  - name: ENV
                    value: "local"
                  - name: LOG_LEVEL
                    value: "debug"
                  - name: ORDER_SERVICE_URL
                    value: "http://order-service"
