apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - argocd-route.yaml

commonLabels:
  app.kubernetes.io/name: platform-gateway
  app.kubernetes.io/component: gateway
  app.kubernetes.io/part-of: platform
