apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forkflow-local

resources:
  - ../../../base/order-service

commonLabels:
  environment: local

replicas:
  - name: order-service
    count: 2

images:
  - name: order-service
    newName: order-service
    newTag: latest

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: order-service
      spec:
        template:
          spec:
            containers:
              - name: order-service
                resources:
                  requests:
                    memory: "128Mi"
                    cpu: "100m"
                  limits:
                    memory: "256Mi"
                    cpu: "500m"
                env:
                  - name: ENV
                    value: "local"
                  - name: LOG_LEVEL
                    value: "debug"
                  - name: CATALOG_SERVICE_URL
                    value: "http://catalog-service"
                  - name: OTEL_EXPORTER_OTLP_ENDPOINT
                    value: "http://jaeger.observability.svc.cluster.local:4317"
