apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - httproutes.yaml

commonLabels:
  app.kubernetes.io/name: observability-gateway
  app.kubernetes.io/component: gateway
  app.kubernetes.io/part-of: observability
